version: '3.7'
services:
  oxen:
    build: .
    image: oxen-docker-oxen
    stdin_open: true
    volumes: 
      - ./.oxen:/root/.oxen
    ports:
      - "22020:22020"    # storage server connectivity (TCP and UDP)
      - "22021:22021"    # client to storage server
      - "22022:22022"    # blockchain syncing
      - "22025:22025"    # Service Node to Service Node
      - "1090:1090/udp"  # Lokinet router data (UDP only)

